language: python
matrix:
    include:
        - python: 3.7
        dist: xenial
        sudo: true

before_script:
        -pip install -r requirements.txt
        
env: DJANGO_SETTINGS_MODULE='OCRnutella.settings'

services:
        -postgresql

script: 
- ./manage.py test

