dist: xenial

language: python
python:
        - '3.7'

before_script:
       - 'pip install -r requirements.txt'
       - 'pip install --upgrade "sentry-sdk==0.13.5"' 
        
env: DJANGO_SETTINGS_MODULE='OCRnutella.settings'

services:
        - postgresql

script: 
        - python manage.py test
