dist: xenial
language: python
python:
        -'3.6.7'

before_script:
        -pip install -r requirements.txt
        -pip install pipenv
        -pip install --dev
env: DJANGO_SETTINGS_MODULE='OCRnutella.settings'

services:
        -postgresql

script: 
- pipenv run python3 manage.py test

