dist: xenial

language: python
python:
        - '3.7'

before_script:
       - 'pip install -r requirements.txt' 
        
env: DJANGO_SETTINGS_MODULE='settings'

services:
        -postgresql

script: 
- python manage.py test

