dist: xenial
language: python

python:
        -'3.6.9'

before_script:
        -pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE='OCRnutella.settings'

services:
        -postgresql

script: 
- ./manage.py test

